'use client';
import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function CadastroPage(){
 const router=useRouter(); const [step,setStep]=useState(1); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault(); const form=new FormData(e.currentTarget); if(step===1){if(form.get('password')!==form.get('confirmPassword')) return setError('As senhas não conferem.'); setError(''); setStep(2); return;} setLoading(true); setError(''); const payload=Object.fromEntries(form.entries()); const r=await fetch('/api/auth/cadastro',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const d=await r.json(); setLoading(false); if(!r.ok)return setError(d.message||'Não foi possível criar a conta.'); router.push('/app/configuracao-inicial'); router.refresh();}
 return <main className="authPage"><form className="card authWide" onSubmit={submit}><Link className="back" href="/login">← Voltar ao login</Link><div className="steps"><span className={step===1?'active':''}>1. Sua conta</span><span className={step===2?'active':''}>2. Seu plano</span></div><h2>Crie sua conta</h2><div className="sub">Comece a organizar seu pet shop em poucos minutos.</div>{error&&<div className="error">{error}</div>}
 <div className={step===1?'':'hidden'}><div className="formGrid"><div className="field"><label>Nome do responsável</label><input name="ownerName" required={step===1}/></div><div className="field"><label>Nome do pet shop</label><input name="companyName" required={step===1}/></div><div className="field"><label>E-mail</label><input name="email" type="email" required={step===1}/></div><div className="field"><label>WhatsApp</label><input name="phone" placeholder="(51) 99999-9999" required={step===1}/></div><div className="field"><label>Senha</label><input name="password" type="password" minLength={8} required={step===1}/></div><div className="field"><label>Confirmar senha</label><input name="confirmPassword" type="password" minLength={8} required={step===1}/></div></div><button className="btn">Continuar</button></div>
 <div className={step===2?'':'hidden'}><div className="planGrid"><label className="plan"><input type="radio" name="plan" value="ESSENCIAL"/><strong>Essencial</strong><b>R$ 129/mês</b><small>Gestão completa para começar.</small></label><label className="plan featured"><span>MAIS ESCOLHIDO</span><input type="radio" name="plan" value="PROFISSIONAL" defaultChecked/><strong>Profissional</strong><b>R$ 179/mês</b><small>Inclui fidelidade completa.</small></label><label className="plan"><input type="radio" name="plan" value="PREMIUM"/><strong>Premium</strong><b>R$ 219/mês</b><small>Automação, campanhas e VIP.</small></label></div><div className="trialNote">Seu período de teste de 2 dias será aplicado automaticamente. Nenhuma cobrança é feita agora.</div><div className="buttonRow"><button type="button" className="btn secondary" onClick={()=>setStep(1)}>Voltar</button><button className="btn" disabled={loading}>{loading?'Criando conta...':'Criar conta e começar'}</button></div></div>
 <p className="legal">Ao criar sua conta, você concorda com os Termos de Uso e a Política de Privacidade.</p></form></main>
}
